version: "3.8"

services:
  csp-scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csp-scrapper
    env_file:
      - ./app/.env
    volumes:
      - ./app/output:/app/output
